apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: broker
  namespace: confluent
spec:
  replicas: 3
  image:
    application: confluentinc/cp-server:7.0.1
    init: confluentinc/confluent-init-container:2.2.0-1
  dataVolumeCapacity: 1Ti
  podTemplate:
    labels:
      version: "7.0.1"
    resources:
      requests:
        cpu: "0.5"
        memory: "2Gi"
      limits:
        cpu: "1"
        memory: "4Gi"
