apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-enterprise-control-center:7.0.1
    init: confluentinc/confluent-init-container:2.2.0-1
  dataVolumeCapacity: 125Gi
  podTemplate:
    labels:
      versions: "7.0.1"
    resources:
      requests:
        cpu: "1"
        memory: "4Gi"
      limits:
        cpu: "2"
        memory: "8Gi"
  dependencies:
    schemaRegistry:
      url: http://schemaregistry.confluent.svc.cluster.local:8081
    ksqldb:
    - name: ksql
      url: http://ksqldb.confluent.svc.cluster.local:8088
    connect:
    - name: connect
      url:  http://connect.confluent.svc.cluster.local:8083
    - name: replicator
      url:  http://replicator.confluent.svc.cluster.local:8083