apiVersion: platform.confluent.io/v1beta1
# Confluent Replicator is built as a connector, and so will use the `Connect` CRD.
kind: Connect
metadata:
  name: replicator
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-enterprise-replicator:7.0.1
    init: confluentinc/confluent-init-container:2.2.0-1
  podTemplate:
    labels:
      version: "7.0.1"
    envVars:
    - name: CLASSPATH
      value: /usr/share/java/kafka-connect-replicator/replicator-rest-extension-7.0.1.jar
    resources:
      requests:
        cpu: "2"
        memory: "8Gi"
      limits:
        cpu: "4"
        memory: "16Gi"
  configOverrides:
    server:
    - rest.extension.classes=io.confluent.connect.replicator.monitoring.ReplicatorMonitoringExtension
  dependencies:
    schemaRegistry:
      url: http://schemaregistry.confluent.svc.cluster.local:8081